"""Initial migration

Revision ID: af6a292d00ca
Revises: 
Create Date: 2025-04-03 13:49:01.835165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6a292d00ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inUAH', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inUSD', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
