"""Expenses edit

Revision ID: e730e37781ef
Revises: af6a292d00ca
Create Date: 2025-04-03 13:54:41.420780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e730e37781ef'
down_revision: Union[str, None] = 'af6a292d00ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Expenses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('inUAH', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inUSD', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('createdAt', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('User')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('inUAH', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('inUSD', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='User_pkey')
    )
    op.drop_table('Expenses')
    # ### end Alembic commands ###
